### ISSUE TITLE
Influx Data Source for Grafana

### ISSUE THREAD

**Issue by singhswat** [vinceskahan/weatherflow-udp-listener#8] opened 2021-02-09 14:16 UTC
Hi,

In the documentation, can you share the steps or details on how to create InfluxDB data source.
[](https://grafana.com/grafana/dashboards/13858/reviews)

I mean what connection params should we use to connect and see the dashboard for pedagogical steps

Thanks
S

**Comment by vinceskahan** [comment] 2021-02-10 00:09
No.  I'd suggest perhaps you might consult Google for the hundreds of HOWTO documents for how to set up influxdb.  Closing this as 'not a bug'

**Closed by vinceskahan** 2021-02-10 00:09 UTC

**Comment by singhswat** [comment] 2021-02-10 00:21
Thanks. I'm still on google - as what connection params should I use to connect to a shared dashboard. If I wish to see data :)
